version: '2'

networks:
  monitor-net:
    driver: bridge

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./data/prometheus/:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-storage.local.memory-chunks=100000'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
    restart: always  

  cadvisor:
    image: google/cadvisor:v0.24.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
    restart: always  

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./data/grafana/:/var/lib/grafana
    env_file:
      - user.config
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
    restart: always  
